### PR TITLE
Task/automated testing

### LINKED ISSUE #82: task/add_automated_tests
Add automated tests

### PR DESCRIPTION
**Pull request by gbudau**
This PR adds integration tests and a workflow to run them.

resolve #82

### CODE REVIEW

**Review by Damrod — APPROVED** [review]
No tengo ni idea de Python. Por lo que veo has hecho una colección de funciones cada una para una prueba concreta... Pero desde donde se llaman estás funciones?
Very cool!

**Comment by gbudau** [comment]
Thank you, @Damrod! Good observation. The `pytest` framework has many ways to run the tests. Currently, we pass the directory with the tests, and it runs them automatically. There is also a way to add the main function. More info [here](https://docs.pytest.org/en/stable/usage.html#specifying-tests-selecting-tests).

**Review by vdedios — APPROVED** [review]
Great having this!! I would love, when we talk, a little master class about this. LGTM :rocket:

**Comment by gbudau** [comment]
Thank you! Sure, whenever you want :100:

**Pull request merged**
